[package]
name = "crossdrop"
version = "0.3.0"
edition = "2024"

[dependencies]
iroh = "0.96.1"
webrtc = "0.17.1"
tokio = { version = "1.49.0", features = ["full"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
bytes = "1.11.1"
futures = "0.3.31"
thiserror = "2.0.18"
anyhow = "1.0.101"
rand = "0.9"
once_cell = "1.21.3"
ratatui = { version = "0.30.0", features = ["crossterm"] }
sha3 = "0.10"
uuid = { version = "1", features = ["v4", "serde"] }
clap = { version = "4", features = ["derive"] }
toml = "0.9.11+spec-1.1.0"
base64 = "0.22"
brotli = "8.0.2"
hex = "0.4"
crossterm = "0.29"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
dirs = "6"
